/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagement;

import java.awt.Color;
import java.awt.Font;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;

/**
 *
 * @author Hp
 */
public class add_app extends javax.swing.JFrame {

    /**
     * Creates new form add_app
     */
    String idd;

    public add_app(String id) {
        initComponents();
        idd = id;
        setapp();
        jLabel2.setVisible(false);
    }
    String doc;
    String mename;

    public void setapp() {

        try {
            String line;
            BufferedReader br = new BufferedReader(new FileReader("patients.csv"));
            while ((line = br.readLine()) != null) {
                String values[] = line.split(",");
                if (values[0].equals(idd)) {
                    doc = values[3];
                    mename = values[1];
                    break;
                }
            }
            br.close();
        } catch (FileNotFoundException e) {
            System.out.println("patients not found");
        } catch (IOException ex) {
            System.out.println("god knpws wat");
        }

        try {
            String line;
            BufferedReader br = new BufferedReader(new FileReader("slots.csv"));
            while ((line = br.readLine()) != null) {
                String values[] = line.split(",");
                if (values[0].equals(doc)) {
                    for (int i = 1; i < values.length; i++) {
                        slot.addItem(values[i]);
                    }
                }
            }
            br.close();
        } catch (FileNotFoundException e) {
            System.out.println("slots not found");

        } catch (IOException ex) {
            System.out.println("god knpws wat2");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slot = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slot.setBackground(new java.awt.Color(29, 164, 196));
        slot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        slot.setForeground(new java.awt.Color(255, 255, 255));
        slot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Time Slot" }));
        slot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotActionPerformed(evt);
            }
        });
        getContentPane().add(slot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 180, 40));

        jButton1.setBackground(new java.awt.Color(29, 164, 196));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Book");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 100, 40));

        jButton2.setBackground(new java.awt.Color(29, 164, 196));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/Best-FreeOpen-Source-Hospital-Management-System-02-1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1100, 520));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
        new pat_logged(idd).setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void slotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slotActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String time = (String) slot.getSelectedItem();
        String line;
        
        if(time.equals("Time Slot")){
            slot.setBorder(new LineBorder(Color.RED));
            
        }
        else{
        try {
            File newfile = new File("temp.csv");
            File oldfile = new File("slots.csv");
            FileWriter fw = new FileWriter(newfile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);

            BufferedReader br = new BufferedReader(new FileReader("slots.csv"));
            while ((line = br.readLine()) != null) {
                String values[] = line.split(",");
                if (values[0].equals(doc)) {
                    pw.print(doc);
                    for (int i = 1; i < values.length; i++) {
                        if (!values[i].equals(time)) {
                            pw.print("," + values[i]);
                        }
                    }
                    pw.println();

                } else {
                    pw.println(line);
                }

            }
            pw.flush();
            pw.close();
            br.close();
            bw.close();
            fw.close();
            System.out.println("updated");
            String xx = oldfile.getAbsolutePath();

            oldfile.delete();

            if (oldfile.exists()) {
                System.out.println("not deleted");
            }
            File dump = new File(xx);

            newfile.renameTo(dump);
            jLabel2.setText("Slot Booked");
        } catch (IOException ex) {
            System.out.println("yayan se");

        }

        try {
       
            File oldfile = new File("app.csv");
            FileWriter fw = new FileWriter(oldfile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
           
            pw.println(doc + "," + idd+ "," + mename + "," + time);

            pw.flush();
            pw.close();
            bw.close();
            fw.close();
            System.out.println("updated");
            String xx = oldfile.getAbsolutePath();

            jLabel2.setVisible(true);
            jLabel2.setText("Slot Booked");
            System.out.println("app updated");
            slot.removeAllItems();
            setapp();

        } catch (IOException ex) {
            System.out.println("yayan se");

        }
        }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_app(" ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> slot;
    // End of variables declaration//GEN-END:variables
}
